[package]
name = "shimmer_egui"
version = "0.1.0"
edition = "2021"

[dependencies]
shimmer_core = { path = "../shimmer_core" }
eframe = { version = "0.27", default-features = false, features = [
    "wgpu",
    "default_fonts",
    "x11",
    "wayland",
] }
egui_dock = "0.12"
strum = { version = "0.26.1", features = ["derive"] }
parking_lot = "0.12.1"
colorous = "1.0.12"
tikv-jemallocator = "0.5.4"
egui_commonmark = { version = "0.15.0", default-features = false, features = [
    "pulldown_cmark",
] }
egui_virtual_list = "0.3.0"
